"use client"

import { useState } from "react"
import { Card } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Label } from "@/components/ui/label"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Textarea } from "@/components/ui/textarea"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Copy, Trash2, Plus, Info, Shield, Terminal } from "lucide-react"
import { useLanguage } from "@/contexts/language-context"
import { Alert, AlertDescription } from "@/components/ui/alert"

interface FirewallRule {
  id: string
  action: "ACCEPT" | "DROP" | "REJECT"
  protocol: "tcp" | "udp" | "icmp" | "all"
  source: string
  destination: string
  sourcePort: string
  destinationPort: string
  interface?: string
  comment: string
}

const defaultRule: FirewallRule = {
  id: Date.now().toString(),
  action: "ACCEPT",
  protocol: "tcp",
  source: "",
  destination: "",
  sourcePort: "",
  destinationPort: "",
  interface: "",
  comment: "",
}

export function FirewallGenerator() {
  const { t } = useLanguage()
  const [rules, setRules] = useState<FirewallRule[]>([{ ...defaultRule }])
  const [tableName, setTableName] = useState("filter")
  const [chainName, setChainName] = useState("INPUT")
  const [outputFormat, setOutputFormat] = useState<"iptables" | "nftables">("iptables")

  const addRule = () => {
    setRules([...rules, { ...defaultRule, id: Date.now().toString() }])
  }

  const removeRule = (id: string) => {
    setRules(rules.filter((rule) => rule.id !== id))
  }

  const updateRule = (id: string, field: keyof FirewallRule, value: string) => {
    setRules(rules.map((rule) => (rule.id === id ? { ...rule, [field]: value } : rule)))
  }

  const generateIptablesRule = (rule: FirewallRule): string => {
    let command = `iptables -A ${chainName}`

    if (rule.interface) {
      command += ` -i ${rule.interface}`
    }

    if (rule.protocol !== "all") {
      command += ` -p ${rule.protocol}`
    }

    if (rule.source) {
      command += ` -s ${rule.source}`
    }

    if (rule.destination) {
      command += ` -d ${rule.destination}`
    }

    if (rule.sourcePort && (rule.protocol === "tcp" || rule.protocol === "udp")) {
      command += ` --sport ${rule.sourcePort}`
    }

    if (rule.destinationPort && (rule.protocol === "tcp" || rule.protocol === "udp")) {
      command += ` --dport ${rule.destinationPort}`
    }

    command += ` -j ${rule.action}`

    if (rule.comment) {
      command += ` -m comment --comment "${rule.comment}"`
    }

    return command
  }

  const generateNftablesRule = (rule: FirewallRule): string => {
    let command = `nft add rule ${tableName} ${chainName}`

    if (rule.interface) {
      command += ` iifname "${rule.interface}"`
    }

    if (rule.protocol !== "all") {
      command += ` ${rule.protocol}`
    }

    if (rule.source) {
      command += ` ip saddr ${rule.source}`
    }

    if (rule.destination) {
      command += ` ip daddr ${rule.destination}`
    }

    if (rule.sourcePort && (rule.protocol === "tcp" || rule.protocol === "udp")) {
      command += ` ${rule.protocol} sport ${rule.sourcePort}`
    }

    if (rule.destinationPort && (rule.protocol === "tcp" || rule.protocol === "udp")) {
      command += ` ${rule.protocol} dport ${rule.destinationPort}`
    }

    command += ` ${rule.action.toLowerCase()}`

    if (rule.comment) {
      command += ` comment "${rule.comment}"`
    }

    return command
  }

  const generateFullScript = (): string => {
    if (outputFormat === "iptables") {
      let script = "#!/bin/bash\n\n"
      script += "# Firewall rules generated by IT Tools\n"
      script += "# Table: filter, Chain: " + chainName + "\n\n"
      script += "# Flush existing rules (optional - be careful!)\n"
      script += `# iptables -F ${chainName}\n\n`
      script += "# Default policy (optional)\n"
      script += `# iptables -P ${chainName} DROP\n\n`
      script += "# Rules:\n"
      rules.forEach((rule) => {
        script += generateIptablesRule(rule) + "\n"
      })
      script += "\n# Save rules (depends on your distribution)\n"
      script += "# For Debian/Ubuntu: iptables-save > /etc/iptables/rules.v4\n"
      script += "# For CentOS/RHEL: service iptables save\n"
      return script
    } else {
      let script = "#!/bin/bash\n\n"
      script += "# Firewall rules generated by IT Tools\n"
      script += "# Table: " + tableName + ", Chain: " + chainName + "\n\n"
      script += "# Create table and chain (if not exists)\n"
      script += `nft create table ${tableName}\n`
      script += `nft create chain ${tableName} ${chainName} { type filter hook input priority 0; }\n\n`
      script += "# Rules:\n"
      rules.forEach((rule) => {
        script += generateNftablesRule(rule) + "\n"
      })
      script += "\n# List all rules\n"
      script += `nft list table ${tableName}\n`
      return script
    }
  }

  const copyToClipboard = (text: string) => {
    navigator.clipboard.writeText(text)
  }

  return (
    <div className="space-y-6">

      <Tabs value={outputFormat} onValueChange={(v) => setOutputFormat(v as "iptables" | "nftables")}>
        <TabsList>
          <TabsTrigger value="iptables">iptables</TabsTrigger>
          <TabsTrigger value="nftables">nftables</TabsTrigger>
        </TabsList>

        <TabsContent value="iptables" className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label>{t("tools.firewall.chain")}</Label>
              <Input value={chainName} onChange={(e) => setChainName(e.target.value)} placeholder="INPUT" />
            </div>
          </div>
        </TabsContent>

        <TabsContent value="nftables" className="space-y-4">
          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <Label>{t("tools.firewall.table")}</Label>
              <Input value={tableName} onChange={(e) => setTableName(e.target.value)} placeholder="filter" />
            </div>
            <div>
              <Label>{t("tools.firewall.chain")}</Label>
              <Input value={chainName} onChange={(e) => setChainName(e.target.value)} placeholder="INPUT" />
            </div>
          </div>
        </TabsContent>
      </Tabs>

      <div className="space-y-4">
        {rules.map((rule, index) => (
          <Card key={rule.id} className="p-6">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-semibold">{t("tools.firewall.rule")} #{index + 1}</h3>
              <Button variant="ghost" size="sm" onClick={() => removeRule(rule.id)}>
                <Trash2 className="w-4 h-4" />
              </Button>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
              <div>
                <Label>{t("tools.firewall.action")}</Label>
                <Select value={rule.action} onValueChange={(v) => updateRule(rule.id, "action", v)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="ACCEPT">ACCEPT</SelectItem>
                    <SelectItem value="DROP">DROP</SelectItem>
                    <SelectItem value="REJECT">REJECT</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>{t("tools.firewall.protocol")}</Label>
                <Select value={rule.protocol} onValueChange={(v) => updateRule(rule.id, "protocol", v)}>
                  <SelectTrigger>
                    <SelectValue />
                  </SelectTrigger>
                  <SelectContent>
                    <SelectItem value="tcp">TCP</SelectItem>
                    <SelectItem value="udp">UDP</SelectItem>
                    <SelectItem value="icmp">ICMP</SelectItem>
                    <SelectItem value="all">{t("tools.firewall.all")}</SelectItem>
                  </SelectContent>
                </Select>
              </div>

              <div>
                <Label>{t("tools.firewall.source")}</Label>
                <Input
                  value={rule.source}
                  onChange={(e) => updateRule(rule.id, "source", e.target.value)}
                  placeholder="192.168.1.0/24 or leave empty"
                />
              </div>

              <div>
                <Label>{t("tools.firewall.destination")}</Label>
                <Input
                  value={rule.destination}
                  onChange={(e) => updateRule(rule.id, "destination", e.target.value)}
                  placeholder="192.168.1.100 or leave empty"
                />
              </div>

              <div>
                <Label>{t("tools.firewall.sourcePort")}</Label>
                <Input
                  value={rule.sourcePort}
                  onChange={(e) => updateRule(rule.id, "sourcePort", e.target.value)}
                  placeholder="80, 443, 8080 or 1000:2000"
                />
              </div>

              <div>
                <Label>{t("tools.firewall.destinationPort")}</Label>
                <Input
                  value={rule.destinationPort}
                  onChange={(e) => updateRule(rule.id, "destinationPort", e.target.value)}
                  placeholder="80, 443, 8080 or 1000:2000"
                />
              </div>

              <div>
                <Label>{t("tools.firewall.interface")}</Label>
                <Input
                  value={rule.interface || ""}
                  onChange={(e) => updateRule(rule.id, "interface", e.target.value)}
                  placeholder="eth0, wlan0 (optional)"
                />
              </div>

              <div>
                <Label>{t("tools.firewall.comment")}</Label>
                <Input
                  value={rule.comment}
                  onChange={(e) => updateRule(rule.id, "comment", e.target.value)}
                  placeholder={t("tools.firewall.commentPlaceholder")}
                />
              </div>
            </div>

            <div className="mt-4 p-3 bg-muted rounded-lg">
              <div className="flex items-center justify-between mb-2">
                <span className="text-sm font-mono text-muted-foreground">
                  {outputFormat === "iptables" ? "iptables" : "nftables"}
                </span>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={() =>
                    copyToClipboard(
                      outputFormat === "iptables" ? generateIptablesRule(rule) : generateNftablesRule(rule)
                    )
                  }
                >
                  <Copy className="w-4 h-4 mr-2" />
                  {t("tools.firewall.copy")}
                </Button>
              </div>
              <code className="text-sm font-mono">
                {outputFormat === "iptables" ? generateIptablesRule(rule) : generateNftablesRule(rule)}
              </code>
            </div>
          </Card>
        ))}

        <Button onClick={addRule} variant="outline" className="w-full">
          <Plus className="w-4 h-4 mr-2" />
          {t("tools.firewall.addRule")}
        </Button>
      </div>

      <Card className="p-6">
        <div className="flex items-center justify-between mb-4">
          <h3 className="font-semibold">{t("tools.firewall.fullScript")}</h3>
          <Button onClick={() => copyToClipboard(generateFullScript())}>
            <Copy className="w-4 h-4 mr-2" />
            {t("tools.firewall.copyScript")}
          </Button>
        </div>
        <Textarea
          value={generateFullScript()}
          readOnly
          className="font-mono text-sm min-h-[300px]"
        />
      </Card>

      <Alert>
        <Info className="h-4 w-4" />
        <AlertDescription>
          <div className="space-y-2">
            <p className="font-semibold">{t("tools.firewall.cheatsheet.title")}</p>
            <div className="space-y-1 text-sm">
              <p><strong>iptables:</strong> {t("tools.firewall.cheatsheet.iptables")}</p>
              <p><strong>nftables:</strong> {t("tools.firewall.cheatsheet.nftables")}</p>
              <p><strong>{t("tools.firewall.cheatsheet.common")}:</strong> {t("tools.firewall.cheatsheet.commonDesc")}</p>
            </div>
          </div>
        </AlertDescription>
      </Alert>
    </div>
  )
}